import java.lang.Math;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;
import java.util.Random;
import java.util.StringTokenizer;
import java.util.*;
import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author shubham
 */
public class Frame2 extends javax.swing.JFrame {
    int upv,dv,aid;
    /**
     * Creates new form Frame2
     */
    public Frame2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SearchBar = new javax.swing.JTextField();
        Topics = new javax.swing.JButton();
        Heading = new javax.swing.JLabel();
        PicLoader = new javax.swing.JPanel();
        ImageDisplayer = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ArticleDisplayer = new javax.swing.JTextArea();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        upvote = new javax.swing.JButton();
        downvote = new javax.swing.JButton();
        CommentDisplayer = new javax.swing.JButton();
        Logout = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        combox = new javax.swing.JTextArea();
        ComDisp = new javax.swing.JLabel();
        ComDisplayer = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        NameDisplayer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        SearchBar.setText("Search...");
        SearchBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchBarMouseClicked(evt);
            }
        });
        SearchBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBarActionPerformed(evt);
            }
        });

        Topics.setText("Topics");
        Topics.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TopicsMouseClicked(evt);
            }
        });
        Topics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TopicsActionPerformed(evt);
            }
        });

        Heading.setFont(new java.awt.Font("URW Palladio L", 1, 18)); // NOI18N
        Heading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Heading.setText("Heading");
        Heading.setToolTipText("Heading");
        Heading.setAlignmentX(0.5F);

        ImageDisplayer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PW-2014-11-13-Cartlidge-qkd.jpg"))); // NOI18N

        javax.swing.GroupLayout PicLoaderLayout = new javax.swing.GroupLayout(PicLoader);
        PicLoader.setLayout(PicLoaderLayout);
        PicLoaderLayout.setHorizontalGroup(
            PicLoaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PicLoaderLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(ImageDisplayer, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PicLoaderLayout.setVerticalGroup(
            PicLoaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PicLoaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ImageDisplayer, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ArticleDisplayer.setColumns(20);
        ArticleDisplayer.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        ArticleDisplayer.setLineWrap(true);
        ArticleDisplayer.setRows(5);
        ArticleDisplayer.setText("Article Text Goes Here.....");
        ArticleDisplayer.setAutoscrolls(false);
        jScrollPane1.setViewportView(ArticleDisplayer);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 671, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        upvote.setText("Upvote");
        upvote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upvoteActionPerformed(evt);
            }
        });

        downvote.setText("Downvote");
        downvote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downvoteActionPerformed(evt);
            }
        });

        CommentDisplayer.setText("Add Comment");
        CommentDisplayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CommentDisplayerActionPerformed(evt);
            }
        });

        Logout.setText("LogOut");
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutMouseClicked(evt);
            }
        });
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });

        combox.setColumns(20);
        combox.setRows(5);
        jScrollPane2.setViewportView(combox);

        ComDisplayer.setText("No comments yet.");

        jLabel1.setText("Enter comments:-");

        NameDisplayer.setText("Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(PicLoader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(399, 399, 399)
                                .addComponent(upvote, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(downvote, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CommentDisplayer, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(111, 111, 111))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addGap(75, 75, 75)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 742, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(Logout)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 833, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Topics, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(NameDisplayer))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 742, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(553, 553, 553)
                        .addComponent(ComDisp))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(534, 534, 534)
                        .addComponent(ComDisplayer))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(Heading, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Topics)
                    .addComponent(Logout)
                    .addComponent(NameDisplayer))
                .addGap(46, 46, 46)
                .addComponent(Heading, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PicLoader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(ComDisplayer)
                        .addGap(43, 43, 43)
                        .addComponent(ComDisp)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(upvote)
                            .addComponent(downvote)
                            .addComponent(CommentDisplayer))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(23, 23, 23)))
                        .addGap(272, 272, 272))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBarActionPerformed
        // TODO add your handling code here:
        //SearchBar.setText("");
    }//GEN-LAST:event_SearchBarActionPerformed

    private void SearchBarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchBarMouseClicked
        // TODO add your handling code here:
         SearchBar.setText("");
    }//GEN-LAST:event_SearchBarMouseClicked

    private void TopicsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TopicsMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        new Frame3().setVisible(true);
    }//GEN-LAST:event_TopicsMouseClicked

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogoutActionPerformed

    private void LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        new Frame1().setVisible(true);
        
    }//GEN-LAST:event_LogoutMouseClicked

    private void TopicsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TopicsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TopicsActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
     
    }//GEN-LAST:event_formWindowActivated

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
           System.out.println("entered frame 2");
           
        try{
            Class.forName("java.sql.Driver");
            //System.out.println("Correct till here");
            Connection conn=(Connection)  DriverManager.getConnection("jdbc:mysql://localhost:3306/dbmsProject","root","shubh123");
            //System.out.println("Correct till here");
            Statement st=conn.createStatement();
            //String username=usrname.getText().toString();
            //String password=new String(psword.getPassword());
            String query="Select * from users where username = \""+Frame1.uname+"\";";
            System.out.println(query);
            ResultSet rs=st.executeQuery(query);
            String temp="";
            if(rs.next())
            {
                temp=rs.getString("genre");
            }
            int c=0;
            for(int i=0;i<temp.length();i++)
            {
                if(temp.charAt(i)==',')
                    c++;
            }
            String gen="";
            if(c==1)
                gen=temp.substring(0,temp.length()-1);
            else{
                int t=new Random().nextInt(c)+1;
                System.out.println("t="+t);
                StringTokenizer s1t=new StringTokenizer(temp,",");
                for(int i=0;i<t;i++)
                {
                    gen=s1t.nextToken();
                }
            }
            System.out.println("gen="+gen);
            rs.close();
            query="Select * from article where category = \""+gen+"\";";
            System.out.println(query);
            rs=st.executeQuery(query);
            temp="";
            if(rs.next())
            {
                ArticleDisplayer.setText(rs.getString("Content"));
                String com=rs.getString("comment");
                Heading.setText(rs.getString("heading"));
                //ImageDisplayer.
                aid=rs.getInt("article_id");
                upvote.setText("Upvotes | "+rs.getInt("upvote"));
                upv=rs.getInt("upvote");
                downvote.setText("Downvotes | "+rs.getInt("downvote"));
                dv=rs.getInt("downvote");
                int count=0;
                String s="";
                for(int i=0;i<com.length()-1;i++)
                {
                    if(com.charAt(i)=='\\' && com.charAt(i+1)=='n')
                    {
                        s=com.substring(count,i-1);
                        count=i+2;
                        ComDisplayer.setText(ComDisplayer.getText().toString()+"\n"+s);
                    }
                }
            }
            //downvote.setText("dvote");
        }catch (ClassNotFoundException ex) {
            Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
        }catch(SQLException e)
        {
            System.out.println(e.getMessage());
        }
        Heading.setAlignmentX(CENTER_ALIGNMENT);
        
            NameDisplayer.setText("Hello! "+Frame1.uname);
    }//GEN-LAST:event_formWindowOpened

    private void upvoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upvoteActionPerformed
        // TODO add your handling code here:
            try{
            Class.forName("java.sql.Driver");
            //System.out.println("Correct till here");
            Connection conn=(Connection)  DriverManager.getConnection("jdbc:mysql://localhost:3306/dbmsProject","root","shubh123");
            //System.out.println("Correct till here");
            Statement st=conn.createStatement();
            //String username=usrname.getText().toString();
           // String password=new String(psword.getPassword());
          
            upv++;
            String query="Update article set upvote = "+upv+"  where article_id= "+aid+";";
            System.out.println(query);
            PreparedStatement pdt=conn.prepareStatement(query);
            int n1=pdt.executeUpdate();
            upvote.setText("Upvotes | "+upv);
            st.close();
            conn.close();
            
        }catch(SQLException e)
        {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(this, "error in connection");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Frame3.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_upvoteActionPerformed

    private void downvoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downvoteActionPerformed
        // TODO add your handling code here:
            try{
            Class.forName("java.sql.Driver");
            //System.out.println("Correct till here");
            Connection conn=(Connection)  DriverManager.getConnection("jdbc:mysql://localhost:3306/dbmsProject","root","shubh123");
            //System.out.println("Correct till here");
            Statement st=conn.createStatement(); 
            dv++;
            String query="Update article set downvote = "+dv+" where article_id= "+aid+";";
            System.out.println(query);
            PreparedStatement pdt=conn.prepareStatement(query);
            int n1=pdt.executeUpdate();
            downvote.setText("Downvotes | "+dv);
            st.close();
            conn.close();
            
        }catch(SQLException e)
        {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(this, "error in connection");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Frame3.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_downvoteActionPerformed

    private void CommentDisplayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CommentDisplayerActionPerformed
        // TODO add your handling code here:
        if(combox.getText().toString().length()!=0)
        {
            if(ComDisplayer.getText().toString().equals("No comments yet."))
                ComDisplayer.setText(combox.getText().toString());
            else
                ComDisplayer.setText(ComDisplayer.getText().toString()+" \n"
                        + "  \n"+combox.getText().toString());
        }
    }//GEN-LAST:event_CommentDisplayerActionPerformed
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame2().setVisible(true);
           
                /*BufferedImage myPicture = null;
                try {
                    myPicture = ImageIO.read(new File("/home/shubham/480.jpg"));
                } catch (IOException ex) {
                    Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
                }
                jLabel2 = new JLabel(new ImageIcon(myPicture));*/
            }
        });
    }

    public JButton getCommentDisplayer() {
        return CommentDisplayer;
    }

   

    public JButton getTopics() {
        return Topics;
    }

    public JButton getDownvote() {
        return downvote;
    }

    public JTextField getjTextField1() {
        return SearchBar;
    }

    public JButton getUpvote() {
        return upvote;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea ArticleDisplayer;
    private javax.swing.JLabel ComDisp;
    private javax.swing.JLabel ComDisplayer;
    private javax.swing.JButton CommentDisplayer;
    private javax.swing.JLabel Heading;
    private javax.swing.JLabel ImageDisplayer;
    private javax.swing.JButton Logout;
    private javax.swing.JLabel NameDisplayer;
    private javax.swing.JPanel PicLoader;
    private javax.swing.JTextField SearchBar;
    private javax.swing.JButton Topics;
    private javax.swing.JTextArea combox;
    private javax.swing.JButton downvote;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton upvote;
    // End of variables declaration//GEN-END:variables
}
